version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_crm
    restart: always
    environment:
      POSTGRES_USER: jupiter
      POSTGRES_PASSWORD: $tld74367908@!
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
