trigger:
- '*.*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: true  

steps:
# Define the Node.js version to use
- task: UseNode@1
  inputs:
    version: '20.x'  
  displayName: 'Set Node.js version'

# Clean npm cache
- script: npm cache clean --force
  displayName: 'Clean npm cache'

# Remove node_modules and package-lock.json to ensure a clean slate
- script: |
    echo "Removing node_modules and package-lock.json"
    rm -rf node_modules package-lock.json
  displayName: 'Remove node_modules and lock file'

# Install dependencies
- script: |
    echo "Installing dependencies"
    npm install
  displayName: 'Install dependencies'

# Build the project
- script: |
    echo "Building the project"
    npm run build
  displayName: 'Build the project'

# Verify build output before publishing
- script: |
    echo "Listando arquivos no diretório após o build"
    ls -al
    echo "Listando arquivos no diretório de saída (se existir)"
    ls -al out || echo "Diretório 'out' não encontrado"
  displayName: 'Verify build output'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
