trigger:
- '*.*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: true  

steps:
# Define the Node.js version to use
- task: UseNode@1
  inputs:
    version: '20.x'  
  displayName: 'Set Node.js version'

# Clean npm cache
- script: |
    echo "Cleaning npm cache"
    npm cache clean --force
  displayName: 'Clean npm cache'

# Install dependencies
- script: |
    echo "Installing dependencies"
    npm install
  displayName: 'Install dependencies'

# Build the project with Next.js
- script: |
    echo "Building the project"
    npm run build
  displayName: 'Build the project'

# Verify .next directory before publishing
- script: |
    echo "Verifying .next directory"
    if [ ! -d ".next" ]; then
      echo "Error: .next directory not found. Build might have failed."
      exit 1
    fi
    ls -al .next
  displayName: 'Verify build output'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.next'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
