trigger:
- '*.*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: true  

steps:
- task: UseNode@1
  inputs:
    version: '20.x'  
  displayName: 'Set Node.js version'

- script: npm cache clean --force
  displayName: 'Clean npm cache'

- script: rm -rf node_modules package-lock.json
  displayName: 'Remove node_modules and lock file'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'out'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
